masks = [
    "001xxxxxxxxxxxxxxxxxxxxx",
    "000xxxxxxxxxxxxxxxxxxxxxx",
    "100xxxxxxxxxxxxxxxxxxxxxxx",
    "101xxxxxxxxxxxxxxxxxxxxxxxx",
    "001xxxxxxxxxxxxxxxxxxxxxxxxx",
    "110xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "100xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "000xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "101xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "110xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "110xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "111xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "110xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "010xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "111xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "101xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "110xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "010xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "001xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "010xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "110xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "001xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "011xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "010xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "110xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "101xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "010xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "111xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "011xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "001xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "011xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "010xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "001xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
]

masks = [mask.replace('x', '?1') for mask in masks]

for mask in masks:
    print(mask)