masks = [
    "0011xxxxxxxxxxxxxxxxxxxx",
    "0001xxxxxxxxxxxxxxxxxxxxx",
    "1000xxxxxxxxxxxxxxxxxxxxxx",
    "1010xxxxxxxxxxxxxxxxxxxxxxx",
    "0010xxxxxxxxxxxxxxxxxxxxxxxx",
    "1100xxxxxxxxxxxxxxxxxxxxxxxxx",
    "1001xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0000xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1010xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1100xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1111xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1111xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1001xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1011xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0010xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0101xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0011xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0110xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0101xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1101xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1010xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0101xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1110xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0110xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0011xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0110xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1001xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "1001xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "0011xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
]

masks = [mask.replace('x', '?1') for mask in masks]

for mask in masks:
    print(mask)