masks = [
    "00xxxxxxxxxxxxxxxxxxxxxx",
    "00xxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxx",
    "00xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "11xxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "00xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "00xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "00xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "00xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "00xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "00xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "10xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "01xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "00xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
]

masks = [mask.replace('x', '?1') for mask in masks]

for mask in masks:
    print(mask)